substitutions:
  name: atom-echo
  friendly_name: "Atom Echo Base"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  on_boot:
    priority: -100
    then:
      - mqtt.publish:
          topic: atom_echo/status
          payload: "online"
      - light.turn_on:
          id: led
          brightness: 50%
          red: 0%
          green: 100%
          blue: 0%
          effect: "None"
      - delay: 1s
      - light.turn_off: led

globals:
   - id: udp_client
     type: WiFiUDP
     restore_value: no
   - id: is_recording
     type: bool
     restore_value: no
     initial_value: 'false'

esp32:
  board: m5stack-atom
  framework:
    type: arduino

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password

mqtt:
  broker: !secret mqtt_broker
  port: 1883
  client_id: "atom-echo"

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:

ota:
  platform: esphome

light:
  - platform: fastled_clockless
    chipset: SK6812
    pin: GPIO27
    num_leds: 1
    rgb_order: GRB
    name: "Atom Echo LED"
    id: led

# Standard Atom Echo I2S Configuration (Microphone ONLY Test)
i2s_audio:
  - id: i2s_out
    i2s_lrclk_pin: GPIO33
    i2s_bclk_pin: GPIO19

# media_player:
#   - platform: i2s_audio
#     id: echo_player
#     dac_type: external
#     i2s_audio_id: i2s_out
#     i2s_dout_pin: GPIO22
#     mode: stereo

microphone:
  - platform: i2s_audio
    id: echo_mic
    i2s_audio_id: i2s_out
    i2s_din_pin: GPIO23
    adc_type: external
    pdm: true
    channel: right
    sample_rate: 16000

    on_data:
      - lambda: |-
          if (id(is_recording)) {
            // Debug Log
            ESP_LOGD("mic", "Got %d samples", x.size());

            uint8_t *data = (uint8_t *)x.data();
            size_t total_len = x.size() * 2;
            size_t offset = 0;
            // Send in chunks to fit UDP MTU
            while (offset < total_len) {
              size_t chunk_size = total_len - offset;
              if (chunk_size > 1024) chunk_size = 1024;
              if (id(udp_client).beginPacket("192.168.31.193", 5000)) {
                id(udp_client).write(data + offset, chunk_size);
                id(udp_client).endPacket();
              }
              offset += chunk_size;
            }
          }

binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO39
      inverted: true
    name: "Button"
    on_press:
      - light.turn_on:
          id: led
          brightness: 100%
          red: 100%
          green: 0%
          blue: 0%
      - globals.set:
          id: is_recording
          value: 'true'
      - mqtt.publish:
          topic: atom_echo/status
          payload: "recording_start"
    on_release:
      - light.turn_off: led
      - globals.set:
          id: is_recording
          value: 'false'
      - mqtt.publish:
          topic: atom_echo/status
          payload: "recording_stop"

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
